import 'dart:async';
import 'package:flutter/material.dart';
import 'irc_client.dart';
import 'models.dart';
import 'storage.dart';

void main() => runApp(const JersIrcApp());

class JersIrcApp extends StatelessWidget {
  const JersIrcApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(
    title: 'JersIRC', debugShowCheckedModeBanner: false,
    theme: ThemeData(brightness: Brightness.dark, useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF91A7C4), brightness: Brightness.dark),
      scaffoldBackgroundColor: const Color(0xFF11161C), cardColor: const Color(0xFF1A2129)),
    home: const IrcHomePage());
}

class ChatRoom { final String name; final List<IrcMessage> messages = []; final Set<String> users = {}; ChatRoom(this.name); }

class IrcHomePage extends StatefulWidget { const IrcHomePage({super.key}); @override State<IrcHomePage> createState() => _IrcHomePageState(); }
class _IrcHomePageState extends State<IrcHomePage> {
  final client = IrcClient(), storage = JersStorage();
  final host = TextEditingController(text: 'irc.libera.chat'), port = TextEditingController(text: '6697'), nick = TextEditingController(text: 'JersIRC_User'), channelInput = TextEditingController(text: '#libera'), messageInput = TextEditingController();
  final rooms = <String, ChatRoom>{}; final saved = <SavedServer>[]; StreamSubscription<IrcMessage>? sub;
  String? active; bool connected = false, connecting = false; String status = 'Desconectado';
  ChatRoom get currentRoom => rooms[active] ?? ChatRoom(active ?? 'JersIRC');

  @override void initState() { super.initState(); sub = client.messages.listen(onIrc); _loadSaved(); }
  Future<void> _loadSaved() async { final list = await storage.loadServers(); final last = await storage.getLastServer(); if (!mounted) return; setState(() { saved..clear()..addAll(list); if (last != null) { for (final s in list) { if (s.name == last) { _applyServer(s); break; } } } }); }
  void _applyServer(SavedServer s) { host.text=s.host; port.text='${s.port}'; nick.text=s.nickname; if (s.channels.isNotEmpty) channelInput.text=s.channels.first; }
  Future<void> _saveCurrent() async { final name='${host.text.trim()}:${port.text.trim()}'; final s=SavedServer(name:name,host:host.text.trim(),port:int.tryParse(port.text.trim())??6697,nickname:nick.text.trim(),channels:rooms.keys.toList()); saved.removeWhere((x)=>x.name==name); saved.insert(0,s); await storage.saveServers(saved); await storage.setLastServer(name); if(mounted)setState((){}); }
  void onIrc(IrcMessage m) { if (!mounted) return; setState(() {
    if(m.command=='DISCONNECTED'){connected=false;status='Desconectado';return;} if(m.command=='ERROR'){status='Error';return;}
    if(m.command=='JOIN'&&m.params.isNotEmpty){final c=m.params.last;final r=rooms.putIfAbsent(c,()=>ChatRoom(c));if(m.nick!=null)r.users.add(m.nick!);active??=c;}
    if(m.command=='PART'&&m.params.isNotEmpty&&m.nick!=null)rooms[m.params.last]?.users.remove(m.nick);
    if((m.command=='PRIVMSG'||m.command=='NOTICE')&&m.params.isNotEmpty){final target=m.params.first.startsWith('#')?m.params.first:(m.nick??'Privado');rooms.putIfAbsent(target,()=>ChatRoom(target)).messages.add(m);active??=target;}
    if(m.command=='353'&&m.params.length>=3){final r=rooms.putIfAbsent(m.params[2],()=>ChatRoom(m.params[2]));r.users.addAll(m.trailing.split(RegExp(r'\s+')).where((x)=>x.isNotEmpty).map((x)=>x.replaceFirst(RegExp(r'^[~&@%+]+'),'')));}
  }); }
  Future<void> connect() async { setState((){connecting=true;status='Conectando...';}); try{await client.connect(host:host.text.trim(),port:int.tryParse(port.text.trim())??6697,nickname:nick.text.trim(),secure:true);await _saveCurrent();if(mounted)setState((){connected=true;status='Conectado';});}catch(_){if(mounted)setState(()=>status='Error de conexión');}if(mounted)setState(()=>connecting=false); }
  Future<void> disconnect() async { await client.disconnect(); if(mounted)setState((){connected=false;status='Desconectado';}); }
  void join(){final c=channelInput.text.trim();if(!connected||c.isEmpty)return;rooms.putIfAbsent(c,()=>ChatRoom(c));active=c;client.join(c);_saveCurrent();setState((){});}
  void sendMessage(){final text=messageInput.text.trim(),c=active;if(text.isEmpty||c==null||!connected)return;if(text.startsWith('/')){handleCommand(text);}else{client.message(c,text);rooms[c]!.messages.add(IrcMessage(':${nick.text}!local@local',nick.text,'PRIVMSG',[c,text]));setState((){});}messageInput.clear();}
  void handleCommand(String text){final p=text.substring(1).split(RegExp(r' +'));final cmd=p.first.toLowerCase();if(cmd=='join'&&p.length>1){channelInput.text=p[1];join();}else if(cmd=='part'&&active!=null)client.part(active!);else if(cmd=='nick'&&p.length>1){client.changeNick(p[1]);nick.text=p[1];_saveCurrent();}else if(cmd=='msg'&&p.length>2)client.message(p[1],p.sublist(2).join(' '));else client.send(text.substring(1));}
  @override void dispose(){sub?.cancel();client.dispose();for(final c in[host,port,nick,channelInput,messageInput])c.dispose();super.dispose();}

  @override Widget build(BuildContext context)=>Scaffold(
    appBar:AppBar(backgroundColor:const Color(0xFF151B22),leading:Builder(builder:(c)=>IconButton(icon:const Icon(Icons.menu_rounded),onPressed:()=>Scaffold.of(c).openDrawer())),title:Row(children:[const Icon(Icons.forum_rounded,size:22),const SizedBox(width:8),const Text('JersIRC',style:TextStyle(fontWeight:FontWeight.w700)),if(active!=null)...[const SizedBox(width:12),Text(active!,style:const TextStyle(fontSize:15,color:Colors.white60))]]),actions:[Padding(padding:const EdgeInsets.only(right:12),child:Center(child:Row(children:[Icon(Icons.circle,size:9,color:connected?const Color(0xFF8FB59B):const Color(0xFF777F89)),const SizedBox(width:6),Text(status,style:const TextStyle(fontSize:12,color:Colors.white60))])))]),
    drawer:_drawer(context),body:Column(children:[if(rooms.isNotEmpty)_tabs(),Expanded(child:Row(children:[Expanded(child:active==null?_welcome():_chat()),if(active!=null)_usersPanel()])),_composer()]));
  Widget _tabs()=>SizedBox(height:54,child:Row(children:[Expanded(child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:8),children:[for(final r in rooms.values)Padding(padding:const EdgeInsets.symmetric(horizontal:3,vertical:7),child:ChoiceChip(label:Text(r.name),selected:r.name==active,onSelected:(_)=>setState(()=>active=r.name)))])),SizedBox(width:145,child:Padding(padding:const EdgeInsets.all(6),child:TextField(controller:channelInput,onSubmitted:(_)=>join(),decoration:const InputDecoration(prefixIcon:Icon(Icons.tag,size:18),hintText:'Canal',contentPadding:EdgeInsets.symmetric(horizontal:8))))),IconButton(onPressed:connected?join:null,icon:const Icon(Icons.add_circle_outline))]));
  Widget _drawer(BuildContext context)=>Drawer(backgroundColor:const Color(0xFF151B22),child:SafeArea(child:ListView(padding:const EdgeInsets.all(14),children:[const SizedBox(height:8),const Center(child:Text('JersIRC',style:TextStyle(fontSize:30,fontWeight:FontWeight.w800,letterSpacing:1))),const Center(child:Text('IRC, simple y claro',style:TextStyle(color:Colors.white54))),const SizedBox(height:24),const Text('SERVIDORES GUARDADOS',style:TextStyle(fontSize:12,fontWeight:FontWeight.bold,color:Colors.white54)),const SizedBox(height:8),if(saved.isEmpty)const Text('Aún no hay servidores guardados',style:TextStyle(color:Colors.white38)),...saved.map((s)=>ListTile(dense:true,leading:const Icon(Icons.dns_outlined),title:Text(s.name),subtitle:Text('${s.nickname} · ${s.port}'),onTap:(){_applyServer(s);Navigator.pop(context);})),const SizedBox(height:14),const Divider(color:Colors.white12),const SizedBox(height:14),const Text('CONEXIÓN',style:TextStyle(fontSize:12,fontWeight:FontWeight.bold,color:Colors.white54)),const SizedBox(height:8),TextField(controller:host,decoration:const InputDecoration(labelText:'Servidor')),const SizedBox(height:8),Row(children:[Expanded(child:TextField(controller:port,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Puerto'))),const SizedBox(width:8),Expanded(child:TextField(controller:nick,decoration:const InputDecoration(labelText:'Nickname')))]),const SizedBox(height:12),FilledButton.icon(onPressed:connecting?null:(connected?disconnect:connect),icon:Icon(connected?Icons.link_off:Icons.link),label:Text(connected?'Desconectar':'Conectar con TLS')),const SizedBox(height:24),Center(child:Text('JersIRC',style:TextStyle(fontSize:13,color:Colors.white.withOpacity(.12),fontWeight:FontWeight.bold,letterSpacing:3)))])));
  Widget _welcome()=>Stack(children:[Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.forum_outlined,size:62,color:Colors.white.withOpacity(.45)),const SizedBox(height:14),const Text('Bienvenido a JersIRC',style:TextStyle(fontSize:24,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Conecta un servidor para comenzar',style:TextStyle(color:Colors.white54)),const SizedBox(height:18),Builder(builder:(c)=>OutlinedButton.icon(onPressed:()=>Scaffold.of(c).openDrawer(),icon:const Icon(Icons.settings_outlined),label:const Text('Configurar conexión')))])),Center(child:IgnorePointer(child:Text('JersIRC',style:TextStyle(fontSize:74,fontWeight:FontWeight.w900,color:Colors.white.withOpacity(.025),letterSpacing:8))))]);
  Widget _chat(){final msgs=currentRoom.messages;if(msgs.isEmpty)return Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.tag,size:42,color:Colors.white.withOpacity(.3)),const SizedBox(height:10),Text(currentRoom.name,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const Text('No hay mensajes todavía',style:TextStyle(color:Colors.white54))]));return ListView.builder(padding:const EdgeInsets.fromLTRB(16,12,16,18),itemCount:msgs.length,itemBuilder:(_,i){final m=msgs[i];final mine=m.nick==nick.text;return Padding(padding:const EdgeInsets.symmetric(vertical:5),child:RichText(text:TextSpan(children:[TextSpan(text:'${m.nick??'Sistema'}  ',style:TextStyle(fontWeight:FontWeight.bold,color:mine?const Color(0xFFA9BBD2):const Color(0xFF9CA7B3))),TextSpan(text:m.trailing,style:const TextStyle(color:Colors.white,height:1.35))])));});}
  Widget _usersPanel(){final users=currentRoom.users.toList()..sort();return Container(width:132,decoration:const BoxDecoration(color:Color(0xFF151B22),border:Border(left:BorderSide(color:Colors.white10))),child:ListView(padding:const EdgeInsets.all(10),children:[const Text('USUARIOS',style:TextStyle(fontSize:11,fontWeight:FontWeight.bold,color:Colors.white54)),const SizedBox(height:10),for(final u in users)Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(children:[const Icon(Icons.person_outline,size:15,color:Colors.white38),const SizedBox(width:6),Expanded(child:Text(u,overflow:TextOverflow.ellipsis))]))]));}
  Widget _composer()=>SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(10,8,10,10),child:Row(children:[Expanded(child:TextField(controller:messageInput,enabled:connected&&active!=null,onSubmitted:(_)=>sendMessage(),decoration:InputDecoration(hintText:connected?'Escribe un mensaje o /comando':'Conecta un servidor para chatear',prefixIcon:const Icon(Icons.chat_bubble_outline,size:19),border:OutlineInputBorder(borderRadius:BorderRadius.circular(18))))),const SizedBox(width:8),IconButton.filled(onPressed:connected&&active!=null?sendMessage:null,icon:const Icon(Icons.send_rounded))])));
}
